### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by mrdarkerr** [Freddywhest/TheRealYescoinBot#2]
```
root@ubuntu:~/TheRealYescoinBot# node index.js
/root/TheRealYescoinBot/bot/utils/logger.js:31
  #convertHtmlElementToAnsiColor(message) {
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/TheRealYescoinBot/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by Freddywhest** [comment]
re-download it and try again

**Comment by mrdarkerr** [comment]
I installed the script from the beginning, but the problem was not solved
